name: size-label
on:
    pull_request:
    pull_request_target:
        types: [opened, synchronize]
jobs:
    size-label:
        permissions:
            contents: read
            pull-requests: write
        runs-on: ubuntu-latest
        steps:
            - name: size-label
              uses: 'pascalgn/size-label-action@v0.5.2'
              env:
                  GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
                  IGNORED: |
                      package-lock.json
